# Generated by Django 3.2.3 on 2021-06-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_auto_20210618_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
