# Generated by Django 3.2.3 on 2021-07-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_auto_20210618_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='anxiety',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='depression',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='lifeSatisfaction',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='sleep',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='stress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='test1',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='test2',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='test3',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
