# Generated by Django 3.2.5 on 2021-11-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0006_alter_otp_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='sleep',
        ),
        migrations.AddField(
            model_name='results',
            name='a1',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='a2',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='a3',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='a4',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='a5',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='a6',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='a7',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='d1',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='d2',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='d3',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='d4',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='d5',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='d6',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='d7',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='l1',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='l2',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='l3',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='l4',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='l5',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='w1',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='w2',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='w3',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='w4',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='w5',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='w6',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='w7',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='w8',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
