# Generated by Django 3.2.5 on 2021-12-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0008_auto_20211130_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='test3',
            new_name='visualarray',
        ),
        migrations.RemoveField(
            model_name='results',
            name='test1',
        ),
        migrations.AddField(
            model_name='results',
            name='digitspantest',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='test2',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
