# Generated by Django 3.2.5 on 2021-12-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0010_results_assessment_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitSpanTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField()),
                ('rt', models.IntegerField(null=True)),
                ('recall', models.CharField(max_length=20, null=True)),
                ('stimuli', models.CharField(max_length=50, null=True)),
                ('accuracy', models.CharField(max_length=20, null=True)),
                ('trial_type', models.CharField(max_length=50, null=True)),
                ('trial_index', models.CharField(max_length=20, null=True)),
                ('time_elapsed', models.CharField(max_length=20, null=True)),
                ('internal_node_id', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
