# Generated by Django 3.2.5 on 2021-12-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0011_digitspantestresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitspantestresult',
            name='rt',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
