# Generated by Django 3.2.5 on 2021-12-10 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useraccounts', '0013_visualarraytestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=17)),
                ('dob', models.CharField(max_length=17)),
                ('education', models.CharField(max_length=17)),
                ('org', models.CharField(max_length=17)),
                ('dept', models.CharField(max_length=17)),
                ('cityCountry', models.CharField(max_length=17)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
