from django.db import models
from django.contrib.auth.models import User

# Create your models here.   
  
class Results(models.Model):
    result_id = models.AutoField(primary_key=True)
    anxiety = models.CharField(max_length=50, null=True)
    depression = models.CharField(max_length=50, null=True)
    #sleep = models.CharField(max_length=50, null=True)
    stress = models.CharField(max_length=50, null=True)
    lifeSatisfaction = models.CharField(max_length=50, null=True)
    visualarray = models.CharField(max_length=10000, null=True)
    digitspantest = models.CharField(max_length=5000, null=True)
    test2 = models.CharField(max_length=10000, null=True)
    d1 = models.CharField(max_length=2, null=True)
    d2 = models.CharField(max_length=2, null=True)
    d3 = models.CharField(max_length=2, null=True)
    d4 = models.CharField(max_length=2, null=True)
    d5 = models.CharField(max_length=2, null=True)
    d6 = models.CharField(max_length=2, null=True)
    d7 = models.CharField(max_length=2, null=True)
    a1 = models.CharField(max_length=2, null=True)
    a2 = models.CharField(max_length=2, null=True)
    a3 = models.CharField(max_length=2, null=True)
    a4 = models.CharField(max_length=2, null=True)
    a5 = models.CharField(max_length=2, null=True)
    a6 = models.CharField(max_length=2, null=True)
    a7 = models.CharField(max_length=2, null=True)
    w1 = models.CharField(max_length=2, null=True)
    w2 = models.CharField(max_length=2, null=True)
    w3 = models.CharField(max_length=2, null=True)
    w4 = models.CharField(max_length=2, null=True)
    w5 = models.CharField(max_length=2, null=True)
    w6 = models.CharField(max_length=2, null=True)
    w7 = models.CharField(max_length=2, null=True)
    w8 = models.CharField(max_length=2, null=True)
    l1 = models.CharField(max_length=2, null=True)
    l2 = models.CharField(max_length=2, null=True)
    l3 = models.CharField(max_length=2, null=True)
    l4 = models.CharField(max_length=2, null=True)
    l5 = models.CharField(max_length=2, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    assessment_duration = models.CharField(max_length=10, null=True)
    
class Student(models.Model):
    student_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    roll_no = models.CharField(max_length=10)
    batch = models.CharField(max_length=7)
    semester = models.CharField(max_length=2)
    department = models.CharField(max_length=20)
    year_of_birth = models.CharField(max_length=17)
    email = models.CharField(max_length=20)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    result_id = models.IntegerField(null=True)

class Employee(models.Model):
    employee_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    organization = models.CharField(max_length=50)
    qualification = models.CharField(max_length=7)
    designation = models.CharField(max_length=20)
    year_of_birth = models.CharField(max_length=17)
    email = models.CharField(max_length=20)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    result_id = models.IntegerField(null=True)

class DigitSpanTestResult(models.Model):
    result_id = models.IntegerField(null=False)
    rt = models.CharField(max_length=20, null=True)
    recall = models.CharField(max_length=20, null=True)
    stimuli	= models.CharField(max_length=50, null=True)
    accuracy = models.CharField(max_length=20, null=True)
    trial_type = models.CharField(max_length=50, null=True)
    trial_index	= models.CharField(max_length=20, null=True)
    time_elapsed = models.CharField(max_length=20, null=True)	
    internal_node_id = models.CharField(max_length=50, null=True)

class VisualArrayTestResult(models.Model):
    result_id = models.IntegerField(null=False)
    rt = models.CharField(max_length=20, null=True)
    trial_type = models.CharField(max_length=50, null=True)
    trial_index	= models.CharField(max_length=20, null=True)
    time_elapsed = models.CharField(max_length=20, null=True)
    set_size = models.CharField(max_length=20, null=True)	
    locations = models.CharField(max_length=500, null=True)
    colours	= models.CharField(max_length=500, null=True)
    correct	= models.CharField(max_length=20, null=True)
    key_press = models.CharField(max_length=20, null=True)
    target_different = models.CharField(max_length=20, null=True)
